name: First Workflow
on: 
  push:
    branches:
      - main
jobs:
  first-job:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Print greeting
        run: echo "Hello World!"
      - name: Print goodbye
        run: echo "Done - bye!"
  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checking
        run: echo "::debug::This is a debug message"
